the_strength_shop/about/urls.py
from django.urls import path, include
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.SendEmail, name='about_home'),
]

the_strength_shop/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout", kwargs={'next_page': '/'}),
]

the_strength_shop/apparel/urls.py
from django.urls import path, include
from . import views

app_name = 'apparel'

urlpatterns = [
    path('', views.ApparelListPage.as_view(), name='apparel_list'),
]

the_strength_shop/blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogHomePage.as_view(), name='blog_home'),
]

the_strength_shop/membership/urls.py
from django.urls import path, include
from . import views

app_name = 'membership'

urlpatterns = [
    path('', views.MembershipHomePage.as_view(), name='membership_home'),
]

the_strength_shop/the_strength_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('thanks', views.ThanksPage.as_view(), name='thanks'),
    path('membership/', include('membership.urls', namespace='membership')),
    path('apparel/', include('apparel.urls', namespace='apparel')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('about/', include('about.urls', namespace='about')),
]

the_strength_shop/about/models.py
from django.db import models

# Create your models here.

class EmailReachOuts(models.Model):
    first_name = models.CharField(blank=False, max_length=50)
    last_name = models.CharField(blank=True, max_length=50)
    email = models.EmailField(blank=False, max_length=256)
    subject = models.CharField(blank=False, max_length=256)
    message = models.TextField(blank=False)

    def __str__(self):
        return self.subject

the_strength_shop/accounts/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return self.username

the_strength_shop/apparel/models.py
from django.db import models

# Create your models here.

the_strength_shop/blog/models.py
from django.db import models

# Create your models here.

the_strength_shop/membership/models.py
from django.db import models

# Create your models here.

the_strength_shop/about/forms.py
from django.forms import ModelForm
from .models import EmailReachOuts

# Define the class of a form
class EmailReachOutsForm(ModelForm):
    class Meta:
        # Write the name of models for which the form is made
        model = EmailReachOuts
        # Custom fields
        fields = '__all__'

    # # Function will be used for the validation
    # def clean(self):
    #     # Data from the form is fetched using super function
    #     super(EmailReachOutsForm, self).clean()
    #
    #     # Extract field data
    #     first_name = self.cleaned_data.get('first_name')
    #
    #     # Conditions to be met
    #     if len(first_name) < 0:
    #         self._errors['first_name'] = self.error_class(['Required'])
    #
    #     # return any errors if found
    #     return self.cleaned_data

the_strength_shop/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

the_strength_shop/about/views.py
from django.shortcuts import render
from .forms import EmailReachOutsForm

# Create your views here.

owner_email = '15ansonlin@gmail.com'

def SendEmail(request):
    context = {}
    if request.method == 'POST':
        # Get info from forms
        email_form = EmailReachOutsForm(data=request.POST)
        # Check to see if forms are valid
        if email_form.is_valid():
            # Save Email Form to Database
            email_form.save()

            email_form = EmailReachOutsForm()
        else:
            # Form was invalid
            print(email_form.errors)
        context['email_form'] = email_form
    else:
        # Was not an HTTP post so we just render the forms as blank.
        email_form = EmailReachOutsForm()
        context['email_form'] = email_form

    return render(request, 'about/about_home.html', context)

the_strength_shop/accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

the_strength_shop/apparel/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class ApparelListPage(TemplateView):
    template_name = "apparel/apparel_list.html"

the_strength_shop/blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class BlogHomePage(TemplateView):
    template_name = 'blog/blog_home.html'

the_strength_shop/membership/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class MembershipHomePage(TemplateView):
    template_name = "membership/membership_home.html"

the_strength_shop/the_strength_shop/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

the_strength_shop/about/templates/about/about_home.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="jumbotron">
    <div class="container">
      <div class="row align-items-center">
        <div class="col align-self-center">
          <div class="card mb-3">
            <img src="{% static "the_strength_shop/images/SS_Owners.jpg" %}" class="card-img-top" alt="SS Owners">
            <div class="card-body">
              <h1 class="card-title center"><strong>ABOUT</strong></h1>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
          </div>
        </div>
      </div>
      <p></p>
      <div class="row">
        <div class="col-sm-4">
          <h1><strong>Our Gym</strong></h1>
          <h4>1504 S Story St. #2</h4>
          <h4>Boone, IA 50036</h4>
        </div>
        <div class="col-sm-8">
          <div class="card mb-3">
            <img class="ss_location" src="{% static "the_strength_shop/images/SS_Location.jpg" %}" alt="SS Location">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h1><strong>Contact Us</strong></h1>
          <h4>(515) 460-1780</h4>
        </div>
        <div class="col-sm-8">
          <form method="POST" class="emailreachout-form">
            {% csrf_token %}
            {{ email_form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

the_strength_shop/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{# at the terminal, run pip install django-bootstrap4 #}
{% load bootstrap4 %}

{% block content %}
  <div class="jumbotron">
    <div class="container">
      <h1>Sign Up</h1>
      <form method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button type="submit" class="btn btn-primary">Sign Up</button>
        {% endbuttons %}
        <label class="account-status-link" for="login_redirect">Already have an account? </label>
        <a class="account-status-link" id="login_redirect" href="{% url 'accounts:login'%}">Log in</a>
      </form>
    </div>
  </div>
{% endblock %}

the_strength_shop/apparel/templates/apparel/apparel_list.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Apparel Page</h1>
  </div>
{% endblock %}

the_strength_shop/blog/templates/blog/blog_home.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Blog Page</h1>
  </div>
{% endblock %}

the_strength_shop/membership/templates/membership/membership_home.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Membership Page</h1>
  </div>
{% endblock %}

the_strength_shop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>The Strength Shop</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Link Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">

    <!-- CSS Static File -->
    <link rel="stylesheet" href="{% static 'the_strength_shop/css/master.css' %}">

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-custom">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static "the_strength_shop/images/SS_Logo_Black.jpg" %}" alt="The Strength Shop" class="d-inline-block align-top"  width="250" height="95" class="d-inline-block align-top">
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerItems" aria-controls="navbarTogglerItems" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerItems">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a href="{% url 'membership:membership_home' %}">Membership</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'apparel:apparel_list' %}">Apparel</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'blog:blog_home' %}">Blog</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'about:about_home' %}">About</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a href="https://www.instagram.com/thestrengthshopboone/?igshid=1beijm82sjnin" class="fa fa-instagram"></a>
            </li>
            <li class="nav-item">
              <a href="https://m.facebook.com/TheStrengthShop/" class="fa fa-facebook"></a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'accounts:logout' %}">Log out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a href="{% url 'accounts:login' %}">Log in</a>
                <a href="{% url 'accounts:signup' %}">Sign up</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- <div class="container"> -->
      {% block content %}

      {% endblock %}
    <!-- </div> -->

    <!-- TODO: Decide whether or not to keep this??? -->
    <!-- <footer class="footer">
      <div class="container">
        <h1>Just another night at The Strength Shop!</h1>
        <a href="https://www.instagram.com/thestrengthshopboone/?igshid=1beijm82sjnin" class="fa fa-instagram"></a>
        <a href="https://m.facebook.com/TheStrengthShop/" class="fa fa-facebook"></a>
      </div>
    </footer> -->

    <script src="{% static 'the_strength_shop/js/master.js' %}" type="text/javascript"></script>

  </body>
</html>

the_strength_shop/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <!-- <h1>Welcome</h1> -->
  <div class="gallery">
    <div class="img-container">
      <img
        src="{% static "the_strength_shop/images/SS_Entrance_Preview.jpg" %}"
        alt="SS Entrance"
        data-original="{% static "the_strength_shop/images/SS_Entrance.jpg" %}">
    </div>
    <div class="img-container">
      <img
        src="{% static "the_strength_shop/images/SS_Power_Preview.jpg" %}"
        alt="SS Power"
        data-original="{% static "the_strength_shop/images/SS_Power.jpg" %}">
    </div>
    <div class="img-container">
      <img
        src="{% static "the_strength_shop/images/SS_Shirt_Preview.jpg" %}"
        alt="SS Shirt"
        data-original="{% static "the_strength_shop/images/SS_Shirt.jpg" %}">
    </div>
    <div class="img-container">
      <img
        src="{% static "the_strength_shop/images/SS_Moving_Preview.jpg" %}"
        alt="SS Moving"
        data-original="{% static "the_strength_shop/images/SS_Moving.jpg" %}">
    </div>
  </div>
  <div class="modal">
    <img src="{% static "the_strength_shop/images/SS_Entrance.jpg" %}" alt="" class="full-img">
    <p class="caption">asdfghjkl</p>
  </div>
{% endblock %}

the_strength_shop/templates/thanks.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Thanks for visiting The Strength Shop</h1>
  </div>
{% endblock %}